const GETALL = 'BLOG:GETALL'
const ADD = 'BLOG:ADD'
const UPDATE_LIKE = 'BLOG:UPDATE:LIKE'
const REMOVE  = 'BLOG:REMOVE'
const ORDER = 'BLOG:ORDER'


const IN = 'LOG:IN'
const OUT = 'LOG:OUT'

const NOTHING='NOTHING'
const PENDING = 'PENDING'
const SUCCESS = 'SUCCESS'

const LOG = { IN , OUT }
const BLOG =  { GETALL ,ADD ,UPDATE_LIKE,REMOVE ,ORDER }
const STATUS = { NOTHING,PENDING, SUCCESS }

export default  { BLOG , LOG , ORDER ,STATUS }